### PR TITLE
Simple integration with Slack module.

### PR DESCRIPTION
**Pull request by mccrodp**
Here is some initial work on Slack integration for review.

It is a simple notifier plugin that sends the Slack Body view mode to a Slack channel (via Webhook URL) set in the [Slack module](https://www.drupal.org/project/slack) config UI below.
slack-module-config

**Drupal Message:**
message-data-test

**Slack Message sent via Message Notify:**
message-data-slack-test

### CODE REVIEW

**Comment by amitaibu** [comment]
I think it would make more sense to (try) to provide it as a patch to the Slack module. What do you think?

**Comment by mccrodp** [comment]
Ok, can take a look, but not sure I follow. Any more info or suggestion? It needs to be a notifier plugin to integrate with it though, it needs to be trigger from message_notify side? I just cloned the way it was for SMS plugin, any example of the other way around that you're suggesting?

**Comment by amitaibu** [comment]
I mean, move the plugin from this module, to the slack module.

**Comment by jhedstrom** [comment]
Other modules can provide message_notify plugins (in both Drupal 7 and 8). For instance, this module https://www.drupal.org/project/message_digest does that.

**Comment by mccrodp** [comment]
Thank you, will take a look at this tomorrow :)

**Comment by mccrodp** [comment]
It is done https://www.drupal.org/node/2845248 👷  😃

**Comment by jhedstrom** [comment]
Great!

**Pull request closed without merging**
