### PR TITLE
Installing drush with composer instead of pear

### PR DESCRIPTION
**Pull request by bitamar**

### CODE REVIEW

**Comment by RoySegall** [comment]
Try to have a look on this - https://github.com/RoySegall/apps_entity_restrictions/blob/7.x-1.x/.travis.yml#L22-L28
https://github.com/RoySegall/apps_entity_restrictions/blob/7.x-1.x/.travis.yml#L50
and https://github.com/RoySegall/apps_entity_restrictions/blob/7.x-1.x/.travis.yml#L59-L62

**Comment by bitamar** [comment]
אמחייה!

**Comment by RoySegall** [comment]
@bitamar Can you fail one of the just to make sure travis will catch it?

**Comment by bitamar** [comment]
@RoySegall - ^^ Looks good

**Comment by RoySegall** [comment]
@amitaibu Looks good to me Merging.

**Pull request merged**
